### ISSUE TITLE
History of boiler on/off

### ISSUE THREAD

**Issue by sports31415** [lwsrbrts/PoSHive#12]
Hi,

This is a great project, glad BG have left the API all relatively open. I was wondering if you'd come across a way to retrieve history of whether or not the boiler is on/off? On the web page you can see whether or not the boiler has reached its temp (![image](https://user-images.githubusercontent.com/15997590/39449052-ef4728ce-4cbe-11e8-8860-1b702f3d91df.png)) or is heating, this I think is controlled by `working: true` or `working: false` in the request to `https://beekeeper-uk.hivehome.com/1.0/products?after=`. 

However, it only seems to show what the boiler is currently doing...

Thanks for sharing such clear code!

**Comment by lwsrbrts** [comment]
Hi, thanks for reaching out, you're likely correct that the "working" property is suitable to ascertain if the boiler is working, however unfortunately this doesn't translate in to historically captured information that you can then review. It's not recorded anywhere.

The only viable solution currently is to monitor the state of the system at any given moment in time and then record it somewhere in a database. I do provide a function to do exactly that  `GetHeatingState` which takes single variable of the zone name.

The function only uses information from devices to work out what the target temperature is and what the desired temperature is. If it's lower, the relay in the Hive controller is very likely to be on and calling for heat from the boiler. Whether or not the boiler _is_ actually heating is entirely dependent on the state of the boiler. Unfortunately thatkind of information isn't available via the Hive system and likely never will be.

Although there is an accompanying `GetHotwaterState` function, it can only be used to say what the boiler is being asked to do rather than what it is doing. For example, you might be calling for hot water but the tank thermostat has told the boiler to stop heating it because it's at the desired temperature. Hive is still calling for hot water to be heated because it's in your schedule to do so but the boiler isn't actually heating the hot water.

If I were interested in when my boiler was heating (radiators, not water) and when it wasn't, I would schedule a repeating PowerShell script to get the current heating state using `GetHeatingState('Main')` which returns a boolean value (true or false) and then record that in to a database along with the timestamp. It's pointless doing this for hot water since your schedule tells you that already.

I should warn that although there is no obvious API hit limit, hammering the API for information every second is likely to have them a little annoyed so you should limit your information retrieval to once per 2 minutes or preferably less frequent depending on how accurate you need your data to be.

```powershell
Import-Module -Name PoSHive

$HiveUsername = 'me@domain.com'
$HivePassword = 'supersecurepassword'

$Hive = [Hive]::new($HiveUsername, $HivePassword)

$Hive.Login()

$IsHeating = $Hive.GetHeatingState('Main')

# Handle errors
# Write state and timestamp data to database

```

**Comment by sports31415** [comment]
Thanks for getting back to me. I was thinking of polling it and storing the results if there were no other way. Not ideal, but it'll work! Cheers!
